load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "main_lib",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["src/**/*.h"]),
    includes = ["src"],
    copts = ["-std=c++23"],
    deps = [
        "@imgui_local//:imgui",
        "@grpc//:grpc++",
    ],
)

cc_binary(
    name = "main",
    copts = ["-std=c++23"],
    linkopts = [
        "-lglfw",
        "-lvulkan",
        "-ldl",
        "-lpthread",
        # "-lX11",
    ],
    deps = [":main_lib"],
)
