module(name = "main")

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "rules_python", version = "1.8.4")

new_local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
# python.toolchain(
#     is_default = True,
#     python_version = "3.12.3",  # or "3.12", "3.10", etc.
# )

##########################################
# EXTERNAL DEPS
##########################################
# bazel_dep(name = "grpc", version = "1.76.0")  # from BCR, no local override
# bazel_dep(name = "protobuf", version = "33.5")

# Use the vendored ImGui submodule instead of downloading.
new_local_repository(
    name = "imgui_local",
    build_file = "//third_party:imgui.BUILD",
    path = "third_party/imgui",
)

bazel_dep(name = "grpc", version = "")
local_path_override(
    module_name = "grpc",
    path = "third_party/grpc",
)

bazel_dep(name = "protobuf", version = "")
local_path_override(
    module_name = "protobuf",
    path = "third_party/protobuf",
)
