// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace uicontrol {

static const char* GuiService_method_names[] = {
  "/uicontrol.GuiService/GetUpdates",
  "/uicontrol.GuiService/TriggerAction",
};

std::unique_ptr< GuiService::Stub> GuiService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GuiService::Stub> stub(new GuiService::Stub(channel, options));
  return stub;
}

GuiService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetUpdates_(GuiService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_TriggerAction_(GuiService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::uicontrol::UpdateResponse>* GuiService::Stub::GetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::uicontrol::UpdateResponse>::Create(channel_.get(), rpcmethod_GetUpdates_, context, request);
}

void GuiService::Stub::async::GetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty* request, ::grpc::ClientReadReactor< ::uicontrol::UpdateResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::uicontrol::UpdateResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_GetUpdates_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>* GuiService::Stub::AsyncGetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::uicontrol::UpdateResponse>::Create(channel_.get(), cq, rpcmethod_GetUpdates_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>* GuiService::Stub::PrepareAsyncGetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::uicontrol::UpdateResponse>::Create(channel_.get(), cq, rpcmethod_GetUpdates_, context, request, false, nullptr);
}

::grpc::Status GuiService::Stub::TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::uicontrol::ActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::uicontrol::ActionRequest, ::uicontrol::ActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TriggerAction_, context, request, response);
}

void GuiService::Stub::async::TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::uicontrol::ActionRequest, ::uicontrol::ActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TriggerAction_, context, request, response, std::move(f));
}

void GuiService::Stub::async::TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TriggerAction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>* GuiService::Stub::PrepareAsyncTriggerActionRaw(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::uicontrol::ActionResponse, ::uicontrol::ActionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TriggerAction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>* GuiService::Stub::AsyncTriggerActionRaw(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTriggerActionRaw(context, request, cq);
  result->StartCall();
  return result;
}

GuiService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GuiService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< GuiService::Service, ::uicontrol::Empty, ::uicontrol::UpdateResponse>(
          [](GuiService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::uicontrol::Empty* req,
             ::grpc::ServerWriter<::uicontrol::UpdateResponse>* writer) {
               return service->GetUpdates(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GuiService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GuiService::Service, ::uicontrol::ActionRequest, ::uicontrol::ActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GuiService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::uicontrol::ActionRequest* req,
             ::uicontrol::ActionResponse* resp) {
               return service->TriggerAction(ctx, req, resp);
             }, this)));
}

GuiService::Service::~Service() {
}

::grpc::Status GuiService::Service::GetUpdates(::grpc::ServerContext* context, const ::uicontrol::Empty* request, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GuiService::Service::TriggerAction(::grpc::ServerContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace uicontrol
#include <grpcpp/ports_undef.inc>

