// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace uicontrol {

class GuiService final {
 public:
  static constexpr char const* service_full_name() {
    return "uicontrol.GuiService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Continuous updates (Server streams data to Client)
    std::unique_ptr< ::grpc::ClientReaderInterface< ::uicontrol::UpdateResponse>> GetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::uicontrol::UpdateResponse>>(GetUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::uicontrol::UpdateResponse>> AsyncGetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::uicontrol::UpdateResponse>>(AsyncGetUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::uicontrol::UpdateResponse>> PrepareAsyncGetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::uicontrol::UpdateResponse>>(PrepareAsyncGetUpdatesRaw(context, request, cq));
    }
    // Button click action (Simple Request/Response)
    virtual ::grpc::Status TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::uicontrol::ActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::uicontrol::ActionResponse>> AsyncTriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::uicontrol::ActionResponse>>(AsyncTriggerActionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::uicontrol::ActionResponse>> PrepareAsyncTriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::uicontrol::ActionResponse>>(PrepareAsyncTriggerActionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Continuous updates (Server streams data to Client)
      virtual void GetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty* request, ::grpc::ClientReadReactor< ::uicontrol::UpdateResponse>* reactor) = 0;
      // Button click action (Simple Request/Response)
      virtual void TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::uicontrol::UpdateResponse>* GetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::uicontrol::UpdateResponse>* AsyncGetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::uicontrol::UpdateResponse>* PrepareAsyncGetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::uicontrol::ActionResponse>* AsyncTriggerActionRaw(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::uicontrol::ActionResponse>* PrepareAsyncTriggerActionRaw(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::uicontrol::UpdateResponse>> GetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::uicontrol::UpdateResponse>>(GetUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>> AsyncGetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>>(AsyncGetUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>> PrepareAsyncGetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>>(PrepareAsyncGetUpdatesRaw(context, request, cq));
    }
    ::grpc::Status TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::uicontrol::ActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>> AsyncTriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>>(AsyncTriggerActionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>> PrepareAsyncTriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>>(PrepareAsyncTriggerActionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetUpdates(::grpc::ClientContext* context, const ::uicontrol::Empty* request, ::grpc::ClientReadReactor< ::uicontrol::UpdateResponse>* reactor) override;
      void TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response, std::function<void(::grpc::Status)>) override;
      void TriggerAction(::grpc::ClientContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::uicontrol::UpdateResponse>* GetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request) override;
    ::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>* AsyncGetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::uicontrol::UpdateResponse>* PrepareAsyncGetUpdatesRaw(::grpc::ClientContext* context, const ::uicontrol::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>* AsyncTriggerActionRaw(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::uicontrol::ActionResponse>* PrepareAsyncTriggerActionRaw(::grpc::ClientContext* context, const ::uicontrol::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUpdates_;
    const ::grpc::internal::RpcMethod rpcmethod_TriggerAction_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Continuous updates (Server streams data to Client)
    virtual ::grpc::Status GetUpdates(::grpc::ServerContext* context, const ::uicontrol::Empty* request, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* writer);
    // Button click action (Simple Request/Response)
    virtual ::grpc::Status TriggerAction(::grpc::ServerContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUpdates() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUpdates(::grpc::ServerContext* /*context*/, const ::uicontrol::Empty* /*request*/, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUpdates(::grpc::ServerContext* context, ::uicontrol::Empty* request, ::grpc::ServerAsyncWriter< ::uicontrol::UpdateResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TriggerAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TriggerAction() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_TriggerAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TriggerAction(::grpc::ServerContext* /*context*/, const ::uicontrol::ActionRequest* /*request*/, ::uicontrol::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTriggerAction(::grpc::ServerContext* context, ::uicontrol::ActionRequest* request, ::grpc::ServerAsyncResponseWriter< ::uicontrol::ActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUpdates<WithAsyncMethod_TriggerAction<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUpdates() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::uicontrol::Empty, ::uicontrol::UpdateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::uicontrol::Empty* request) { return this->GetUpdates(context, request); }));
    }
    ~WithCallbackMethod_GetUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUpdates(::grpc::ServerContext* /*context*/, const ::uicontrol::Empty* /*request*/, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::uicontrol::UpdateResponse>* GetUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::uicontrol::Empty* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_TriggerAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TriggerAction() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::uicontrol::ActionRequest, ::uicontrol::ActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::uicontrol::ActionRequest* request, ::uicontrol::ActionResponse* response) { return this->TriggerAction(context, request, response); }));}
    void SetMessageAllocatorFor_TriggerAction(
        ::grpc::MessageAllocator< ::uicontrol::ActionRequest, ::uicontrol::ActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::uicontrol::ActionRequest, ::uicontrol::ActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TriggerAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TriggerAction(::grpc::ServerContext* /*context*/, const ::uicontrol::ActionRequest* /*request*/, ::uicontrol::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TriggerAction(
      ::grpc::CallbackServerContext* /*context*/, const ::uicontrol::ActionRequest* /*request*/, ::uicontrol::ActionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetUpdates<WithCallbackMethod_TriggerAction<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUpdates() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUpdates(::grpc::ServerContext* /*context*/, const ::uicontrol::Empty* /*request*/, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TriggerAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TriggerAction() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_TriggerAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TriggerAction(::grpc::ServerContext* /*context*/, const ::uicontrol::ActionRequest* /*request*/, ::uicontrol::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUpdates() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUpdates(::grpc::ServerContext* /*context*/, const ::uicontrol::Empty* /*request*/, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUpdates(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TriggerAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TriggerAction() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_TriggerAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TriggerAction(::grpc::ServerContext* /*context*/, const ::uicontrol::ActionRequest* /*request*/, ::uicontrol::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTriggerAction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUpdates() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetUpdates(context, request); }));
    }
    ~WithRawCallbackMethod_GetUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUpdates(::grpc::ServerContext* /*context*/, const ::uicontrol::Empty* /*request*/, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TriggerAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TriggerAction() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TriggerAction(context, request, response); }));
    }
    ~WithRawCallbackMethod_TriggerAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TriggerAction(::grpc::ServerContext* /*context*/, const ::uicontrol::ActionRequest* /*request*/, ::uicontrol::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TriggerAction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TriggerAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TriggerAction() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::uicontrol::ActionRequest, ::uicontrol::ActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::uicontrol::ActionRequest, ::uicontrol::ActionResponse>* streamer) {
                       return this->StreamedTriggerAction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TriggerAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TriggerAction(::grpc::ServerContext* /*context*/, const ::uicontrol::ActionRequest* /*request*/, ::uicontrol::ActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTriggerAction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::uicontrol::ActionRequest,::uicontrol::ActionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TriggerAction<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetUpdates() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::uicontrol::Empty, ::uicontrol::UpdateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::uicontrol::Empty, ::uicontrol::UpdateResponse>* streamer) {
                       return this->StreamedGetUpdates(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUpdates(::grpc::ServerContext* /*context*/, const ::uicontrol::Empty* /*request*/, ::grpc::ServerWriter< ::uicontrol::UpdateResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetUpdates(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::uicontrol::Empty,::uicontrol::UpdateResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetUpdates<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetUpdates<WithStreamedUnaryMethod_TriggerAction<Service > > StreamedService;
};

}  // namespace uicontrol


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_service_2eproto__INCLUDED
